### ISSUE TITLE
How to use this profiler, I can execute spike pk hello

### ISSUE THREAD

**Issue by WilliamWangPeng** [bat52/rv8_prof#1]
hi dear author,
    It is an honor to write a letter to you,  I  use RISCV compiler riscv64-unknown-elf-gcc to compiler hello_world.c, and the elf-riscv has been got. And I want to use some RISCV profiler , like your profiler 👍 , to get detect the performance of RISCV executable file,  do you know how to do that?

thank you
best regards
William

**Comment by bat52** [comment]
Hi, I have just committed an example and some further comments on the README. Please have a look at it, and let me know if you manage to use it.

In short you simply need to pass the executable binary (not the elf) to the profiler
./rv8_prof.sh hello_world.exe

Beware this does not measure "performances", it rather counts the number of instructions to execute every function. If the processor execute all instructions in a single clock cycle, this can be directly correlated to a time duration.

Regards,
MM

**Comment by WilliamWangPeng** [comment]
> Hi, I have just committed an example and some further comments on the README. Please have a look at it, and let me know if you manage to use it.
> 
> In short you simply need to pass the executable binary (not the elf) to the profiler ./rv8_prof.sh hello_world.exe
> 
> Beware this does not measure "performances", it rather counts the number of instructions to execute every function. If the processor execute all instructions in a single clock cycle, this can be directly correlated to a time duration.
> 
> Regards, MM

thank you so much 👍  💯  🥇   
    I'm trying to compare the difference between RISCV graphics applications with x86 graphics applications, the profiler you have invented gives us a great deal of help, thank you so much again.
   by the way, do you have any idea how to umplement the RISCV GPU ?  

thank you 
best regards
William

**Comment by bat52** [comment]
Hi, I am glad you find this helpful!

>  by the way, do you have any idea how to umplement the RISCV GPU ?

I have no direct experience in implementing GPUs, but I read of a few efforts in that direction:
* [Vortex GPGPU](https://github.com/vortexgpgpu/vortex): targets NVIDIA CUDA API.
* [Bringing OpenCL to Commodity RISC-V CPUs](https://carrv.github.io/2021/papers/CARRV2021_paper_36_Blaise.pdf): it seems rv8_prof might be used with this environment
* Imagination Technologies' [BXE-2-32](https://imaginationtech.com/product/img-bxe-2-32/) proprietary implementation.
* [RV64X] (https://www.eetimes.com/rv64x-a-free-open-source-gpu-for-risc-v/) apparently linked to [pixilica](https://www.pixilica.com/graphics). However despite the open source claims, I could not find available sources.
